"""Generate synthetic test documents for MediScan (task 2.5).

WHY THIS FILE EXISTS
    Decision #010: no real medical documents may ever enter this repo.
    But Sprint 2+ needs realistic files to test against — so we FABRICATE
    them. Every document this script produces is loudly, watermarked-ly
    synthetic. Re-run any time with:

        uv run python tests/fixtures/generate.py

WHAT IT PRODUCES (in tests/fixtures/files/)
    cbc_report.pdf     — 2-page TEXT PDF of a fake CBC panel. Values match
                         the Sprint 1 conftest fixture (Hb 9.8 L, TLC 11.2 H,
                         Platelets 250 N) so extraction tests can assert
                         known numbers.
    scanned_report.pdf — a PDF with NO text layer (drawings only): what a
                         scanner produces. The router must classify it
                         PDF_SCANNED; PyMuPDF must extract ~nothing.
    sample.png         — tiny valid PNG (image upload path).
    sample.jpg         — tiny valid JPEG.
    spoofed.pdf        — PNG bytes wearing a .pdf name. Must be REJECTED
                         by validate_upload (SpoofedFileTypeError).
    corrupt.pdf        — a real PDF truncated mid-file: valid magic bytes,
                         broken body. Passes validation (magic bytes are
                         fine!) but must fail EXTRACTION gracefully —
                         proving validation and parsing are separate walls.
"""

from pathlib import Path

from PIL import Image
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen.canvas import Canvas

OUT = Path(__file__).parent / "files"

# The same synthetic values as tests/conftest.py's sample_cbc_report —
# one source of truth for "what the test document says".
CBC_ROWS = [
    ("Hemoglobin", "9.8", "g/dL", "13.0 - 17.0", "L"),
    ("Total Leukocyte Count", "11.2", "10^3/uL", "4.0 - 11.0", "H"),
    ("Platelet Count", "250", "10^3/uL", "150 - 410", ""),
    ("Hematocrit", "31.2", "%", "40 - 50", "L"),
    ("MCV", "84.5", "fL", "83 - 101", ""),
]


def make_text_lab_pdf(path: Path) -> None:
    """A realistic, obviously-synthetic 2-page CBC lab report with real text."""
    c = Canvas(str(path), pagesize=A4)
    w, h = A4

    # -- page 1: header + results table --
    c.setFont("Helvetica-Bold", 14)
    c.drawString(20 * mm, h - 20 * mm, "DipsAI Diagnostics (SYNTHETIC)")
    c.setFont("Helvetica", 9)
    c.drawString(
        20 * mm,
        h - 26 * mm,
        "SYNTHETIC DOCUMENT FOR SOFTWARE TESTING - NOT A REAL REPORT",
    )
    c.drawString(
        20 * mm,
        h - 34 * mm,
        "Patient: TEST PATIENT (SYNTHETIC)   Age/Sex: 34/M   Sample: EDTA Blood",
    )
    c.setFont("Helvetica-Bold", 12)
    c.drawString(20 * mm, h - 46 * mm, "COMPLETE BLOOD COUNT (CBC)")

    c.setFont("Helvetica-Bold", 9)
    y = h - 56 * mm
    for x, header in [
        (20, "Test"),
        (85, "Result"),
        (110, "Unit"),
        (140, "Reference Range"),
        (180, "Flag"),
    ]:
        c.drawString(x * mm, y, header)
    c.line(20 * mm, y - 2 * mm, 190 * mm, y - 2 * mm)

    c.setFont("Helvetica", 9)
    y -= 8 * mm
    for name, value, unit, ref, flag in CBC_ROWS:
        for x, cell in [(20, name), (85, value), (110, unit), (140, ref), (180, flag)]:
            c.drawString(x * mm, y, cell)
        y -= 7 * mm

    c.setFont("Helvetica", 8)
    c.drawString(
        20 * mm,
        20 * mm,
        "Page 1 of 2 - synthetic data generated by tests/fixtures/generate.py",
    )
    c.showPage()

    # -- page 2: method notes (gives the router a multi-page text PDF) --
    c.setFont("Helvetica-Bold", 11)
    c.drawString(20 * mm, h - 20 * mm, "Method Notes (SYNTHETIC)")
    c.setFont("Helvetica", 9)
    c.drawString(
        20 * mm,
        h - 30 * mm,
        "All values on this document are fabricated for automated testing.",
    )
    c.drawString(
        20 * mm,
        h - 36 * mm,
        "Counting method: simulated. Analyzer: none. Data source: generate.py.",
    )
    c.setFont("Helvetica", 8)
    c.drawString(20 * mm, 20 * mm, "Page 2 of 2")
    c.save()


def make_scanned_style_pdf(path: Path) -> None:
    """A PDF with NO text layer — drawings only, like a scanner output."""
    c = Canvas(str(path), pagesize=A4)
    w, h = A4
    # rectangles and lines only: visually "a document", textually empty
    c.rect(15 * mm, h - 40 * mm, 180 * mm, 25 * mm)
    for i in range(12):
        y = h - 60 * mm - i * 8 * mm
        c.line(20 * mm, y, 185 * mm, y)
    c.showPage()
    c.save()


def make_images(png_path: Path, jpg_path: Path) -> None:
    """Tiny valid PNG and JPEG files for the image-upload path."""
    img = Image.new("RGB", (64, 64), color=(240, 244, 250))
    img.save(png_path, "PNG")
    img.save(jpg_path, "JPEG")


def make_spoofed_pdf(png_source: Path, path: Path) -> None:
    """PNG bytes wearing a .pdf name — validate_upload must reject it."""
    path.write_bytes(png_source.read_bytes())


def make_corrupt_pdf(good_pdf: Path, path: Path) -> None:
    """A real PDF cut off mid-body: valid magic bytes, unparseable rest.

    This file deliberately PASSES validation (its first bytes are honest)
    and must fail at the PARSING wall instead — validation proves safety,
    not parseability. Separate walls, separate tests.
    """
    data = good_pdf.read_bytes()
    path.write_bytes(data[: len(data) // 3])


def make_report_photo(path: Path) -> None:
    """An IMAGE of CBC text — pixels, not characters (task 3.3).

    This is what OCR exists for: the same synthetic values as
    cbc_report.pdf, but drawn onto a bitmap. No text layer exists;
    only recognition can read it. Large canvas + big dark-on-white
    glyphs = a 'good photo' baseline; preprocessing tests degrade it.
    """
    from PIL import ImageDraw, ImageFont

    img = Image.new("RGB", (1400, 1000), color=(255, 255, 255))
    draw = ImageDraw.Draw(img)
    try:
        font_big = ImageFont.load_default(size=44)
        font = ImageFont.load_default(size=34)
    except TypeError:  # older Pillow: no size parameter
        font_big = font = ImageFont.load_default()

    draw.text(
        (60, 40), "DipsAI Diagnostics (SYNTHETIC)", fill=(10, 10, 10), font=font_big
    )
    draw.text((60, 110), "COMPLETE BLOOD COUNT (CBC)", fill=(10, 10, 10), font=font)
    y = 200
    for name, value, unit, ref, flag in CBC_ROWS:
        line = f"{name}   {value} {unit}   ({ref})   {flag}"
        draw.text((60, y), line, fill=(15, 15, 15), font=font)
        y += 70
    draw.text(
        (60, y + 40), "SYNTHETIC DOCUMENT FOR TESTING", fill=(90, 90, 90), font=font
    )
    img.save(path, "PNG")


def make_scanned_cbc_pdf(photo_path: Path, path: Path) -> None:
    """A TRUE synthetic scan: the report photo embedded in a PDF page.

    Unlike scanned_report.pdf (which tests 'no text at all'), this one
    contains pictured text — the router must classify it PDF_SCANNED,
    and the Sprint 3 scanned-PDF path must OCR real content out of it.
    """
    c = Canvas(str(path), pagesize=A4)
    w, h = A4
    c.drawImage(
        str(photo_path),
        10 * mm,
        h - 160 * mm,
        width=190 * mm,
        height=135 * mm,
        preserveAspectRatio=True,
    )
    c.showPage()
    c.save()


def main() -> None:
    OUT.mkdir(exist_ok=True)
    make_text_lab_pdf(OUT / "cbc_report.pdf")
    make_scanned_style_pdf(OUT / "scanned_report.pdf")
    make_images(OUT / "sample.png", OUT / "sample.jpg")
    make_spoofed_pdf(OUT / "sample.png", OUT / "spoofed.pdf")
    make_corrupt_pdf(OUT / "cbc_report.pdf", OUT / "corrupt.pdf")
    make_report_photo(OUT / "report_photo.png")
    make_scanned_cbc_pdf(OUT / "report_photo.png", OUT / "scanned_cbc.pdf")
    for f in sorted(OUT.iterdir()):
        print(f"  {f.name:20} {f.stat().st_size:>7,} bytes")


if __name__ == "__main__":
    main()
